// Curated, hand-maintained map of the react-icons actually used in the app.
//
// Why this exists: importing `* as X from "react-icons/si"` (+tb, +vsc) and spreading the
// whole sets pulled ~4.7 MB of icons into the client bundle (~97% unused, flagged by Lighthouse).
// Named imports below are tree-shakeable, so only these icons ship.
//
// MAINTENANCE: icon names are chosen in Sanity (free-text strings like "SiGithub"). When you
// add a new icon in the CMS, add the matching named import here, otherwise <ReactIcon> renders
// nothing for it. Find icon names at https://react-icons.github.io/react-icons (Si = Simple
// Icons, Tb = Tabler, Vsc = VS Code).
//
// "SiOpenai" is mapped to a Tabler icon, not a Simple Icons one: Simple Icons removed the
// OpenAI logo in the react-icons 5.7.0 sync (brand takedown request), so the CMS-facing key
// stays "SiOpenai" for existing content, but it now resolves to a generic AI stand-in icon.
import type { IconType } from "react-icons";
import {
  SiAppwrite,
  SiAuth0,
  SiBiome,
  SiClaude,
  SiClerk,
  SiConventionalcommits,
  SiDatadog,
  SiEslint,
  SiExpo,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiHibernate,
  SiI18Next,
  SiJavascript,
  SiJest,
  SiMediapipe,
  SiMui,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiOpencv,
  SiPrettier,
  SiPython,
  SiRabbitmq,
  SiRadixui,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiRedux,
  SiRemix,
  SiResend,
  SiSanity,
  SiScikitlearn,
  SiSemanticrelease,
  SiSpring,
  SiStoryblok,
  SiStorybook,
  SiStyledcomponents,
  SiTailwindcss,
  SiTensorflow,
  SiTestinglibrary,
  SiTypescript,
  SiVercel,
  SiVitest,
  SiX,
  SiZod
} from "react-icons/si";
import {
  TbBrain,
  TbBrandFramerMotion,
  TbBrandGithub,
  TbBrandLinkedin,
  TbBrandReactNative,
  TbBrandSupabase,
  TbBrandTailwind,
  TbBrandX,
  TbDeviceMobile,
  TbHeartRateMonitor,
  TbHtml,
  TbRobotFace,
  TbTestPipe,
  TbWaveSine
} from "react-icons/tb";
import { VscDebugConsole, VscTools } from "react-icons/vsc";

export const ICONS = {
  SiAppwrite,
  SiAuth0,
  SiBiome,
  SiClaude,
  SiClerk,
  SiConventionalcommits,
  SiDatadog,
  SiEslint,
  SiExpo,
  SiFirebase,
  SiGit,
  SiGithub,
  SiGithubactions,
  SiHibernate,
  SiI18Next,
  SiJavascript,
  SiJest,
  SiMediapipe,
  SiMui,
  SiNextdotjs,
  SiNodedotjs,
  SiNpm,
  SiOpenai: TbRobotFace,
  SiOpencv,
  SiPrettier,
  SiPython,
  SiRabbitmq,
  SiRadixui,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiReactrouter,
  SiRedux,
  SiRemix,
  SiResend,
  SiSanity,
  SiScikitlearn,
  SiSemanticrelease,
  SiSpring,
  SiStoryblok,
  SiStorybook,
  SiStyledcomponents,
  SiTailwindcss,
  SiTensorflow,
  SiTestinglibrary,
  SiTypescript,
  SiVercel,
  SiVitest,
  SiX,
  SiZod,
  TbBrain,
  TbBrandFramerMotion,
  TbBrandGithub,
  TbBrandLinkedin,
  TbBrandReactNative,
  TbBrandSupabase,
  TbBrandTailwind,
  TbBrandX,
  TbDeviceMobile,
  TbHeartRateMonitor,
  TbHtml,
  TbTestPipe,
  TbWaveSine,
  VscDebugConsole,
  VscTools
} as const satisfies Record<string, IconType>;

export type IconName = keyof typeof ICONS;
